version: '3.7'

services:
  app:
    build:
      context: .

    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=django-insecure-2%&dj3a6*h$p*%j=*k4n-@r&yp-1nqru404ja2ub$j&ngl5jrm
      - ALLOWED_HOSTS=127.0.0.1,localhost

  proxy:
    build:
      context: ./proxy

    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bobo
      POSTGRES_USER: bobo
      POSTGRES_DB: eat_me_db
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ./postgresql:/var/lib/postgresql/data

volumes:
  static_data:

