# Generated by Django 4.2.3 on 2023-07-15 19:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('protein', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
