# Generated by Django 4.2.3 on 2023-07-17 21:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_photos')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('goal', models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Gain Weight', 'Gain Weight'), ('Maintain Weight', 'Maintain Weight')], max_length=30)),
                ('activity', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately Active'), ('Very Active', 'Very Active'), ('Extra Active', 'Extra Active')], max_length=30)),
                ('calories', models.IntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('protein', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
