# Generated by Django 4.2.3 on 2023-07-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='account',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
