# Generated by Django 4.2.3 on 2023-07-29 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_savedrecipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast_plan', to='recipes.recipe')),
                ('dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_plan', to='recipes.recipe')),
                ('lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_plan', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
