# Generated by Django 4.2.3 on 2023-07-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eating_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatingplan',
            name='total_calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eatingplan',
            name='total_carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eatingplan',
            name='total_fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eatingplan',
            name='total_proteins',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
