# Generated by Django 4.2.3 on 2023-07-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': [('approve_recipe', 'Can approve recipes for sharing')]},
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurements',
            field=models.CharField(choices=[('1', 'grams'), ('1000', 'kilograms')], max_length=21),
        ),
    ]
