# Generated by Django 4.2.3 on 2023-07-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories_per_gram',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs_per_gram',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fats_per_gram',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteins_per_gram',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='proteins',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
