# Generated by Django 4.2.3 on 2023-07-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_calories_per_gram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
